[theme]
base="light"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
primaryColor="#FF4B4B"
textColor="#000000"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
